fix!: change `module` from `ES2022` to `Node16` in TSConfig
This prevents the following error and shouldn't be a difference for most projects. As it could be breaking for some projects, it's released as a breaking change.

tsconfig.json(4,15): error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.